[package]
name = "yizhan-plugin-wechat"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.36"
yizhan-plugin = { path = "../yizhan-plugin" }
yizhan-protocol = { path = "../yizhan-protocol" }

[target.'cfg(windows)'.dependencies]
anyhow = "1.0.61"
serde = { version = "1.0.143", features = ["serde_derive"] }
sysinfo = "0.25.2"
widestring = "1.0.2"
windows-sys = { version = "0.36.1", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_Diagnostics_Debug", "Win32_System_ProcessStatus", "Win32_Storage_FileSystem"] }
