[package]
name = "yizhan-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.61"
async-trait = "0.1.57"
bincode = "2.0.0-rc.1"
clap = { version = "3.2.17", features = ["derive"] }
futures = "0.3.23"
log = "0.4.17"
serde = "1.0.143"
simple_logger = "2.2.0"
tokio = { version = "1.20.1", features = ["macros", "net", "rt-multi-thread", "io-std", "io-util", "sync", "time"] }
yizhan-bootstrap = { path = "../yizhan-bootstrap" }
yizhan-protocol = { path = "../yizhan-protocol" }

[build-dependencies]
winres = "0.1.12"
