[package]
name = "yizhan-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.61"
async-trait = "0.1.57"
bincode = "1.3.3"
tokio = { version = "1.20.1", features = ["macros", "net", "rt-multi-thread", "io-std", "io-util", "sync"] }
yizhan-bootstrap = { path = "../yizhan-bootstrap" }
yizhan-protocol = { path = "../yizhan-protocol" }

[build-dependencies]
winres = "0.1.12"
