[package]
name = "yizhan-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.61"
async-trait = "0.1.57"
bincode = "2.0.0-rc.1"
bytes = "1.2.1"
clap = { version = "3.2.17", features = ["derive"] }
futures = "0.3.23"
machine-uid = "0.2.0"
nanoid = "0.4.0"
network-interface = { git = "https://github.com/EstebanBorai/network-interface.git" }
random-names = { git = "https://github.com/hamflx/random-names-rs" }
serde = "1.0.143"
sha256 = "1.0.3"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["macros", "net", "rt-multi-thread", "io-std", "io-util", "sync", "time"] }
toml = "0.5.9"
tracing = "0.1.36"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.15"
yizhan-bootstrap = { path = "../yizhan-bootstrap" }
yizhan-common = { path = "../yizhan-common" }
yizhan-plugin = { path = "../yizhan-plugin" }
yizhan-plugin-poweroff = { path = "../yizhan-plugin-poweroff" }
yizhan-protocol = { path = "../yizhan-protocol" }

[target.'cfg(windows)'.dependencies]
libc = "0.2.132"
widestring = "1.0.2"
windows-sys = { version = "0.36.1", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_Console"] }
yizhan-plugin-wechat = { path = "../yizhan-plugin-wechat" }

[build-dependencies]
chrono = "0.4.22"
winres = "0.1.12"
