[package]
name = "yizhan-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.61"
async-trait = "0.1.57"
bincode = "2.0.0-rc.1"
clap = { version = "3.2.17", features = ["derive"] }
futures = "0.3.23"
nanoid = "0.4.0"
random-names = { git = "https://github.com/hamflx/random-names-rs" }
serde = "1.0.143"
sha256 = "1.0.3"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["macros", "net", "rt-multi-thread", "io-std", "io-util", "sync", "time"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
yizhan-bootstrap = { path = "../yizhan-bootstrap" }
yizhan-protocol = { path = "../yizhan-protocol" }

[build-dependencies]
chrono = "0.4.22"
winres = "0.1.12"
